USE EMAIL_APP_DB;

INSERT INTO folders (FOLDER_NAME)
VALUES ("Inbox");

INSERT INTO folders (FOLDER_NAME)
VALUES ("Sent");

INSERT INTO EMAILADRESSES (ADRESS_NAME)
VALUES ("send.1642705@gmail.com");

