USE EMAIL_APP_DB;


DROP TABLE IF EXISTS EMAILS_TO_EMAILADRESSES;
DROP TABLE IF EXISTS EMAILS_CC_EMAILADRESSES;
DROP TABLE IF EXISTS EMAILS_BCC_EMAILADRESSES;
DROP TABLE IF EXISTS EMAILS_EMBEDED_ATTACHMENTS;
DROP TABLE IF EXISTS EMAILS_ATTACHMENTS;
DROP TABLE IF EXISTS EMAILS;
DROP TABLE IF EXISTS FOLDERS;
DROP TABLE IF EXISTS ATTACHMENTS;
DROP TABLE IF EXISTS EMAILADRESSES;


CREATE TABLE FOLDERS (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FOLDER_NAME varchar(250) NOT NULL

);

CREATE TABLE EMAILADRESSES (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  AUTHOR_NAME varchar(250) DEFAULT '' ,  
  ADRESS_NAME varchar(250) NOT NULL DEFAULT '' 

);

CREATE TABLE ATTACHMENTS (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ATTACHMENT_NAME varchar(250) NOT NULL,
  ATTACHMENT_DATA mediumblob NOT NULL

);


CREATE TABLE EMAILS (
  ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SENDER_EMAILADRESS_ID int,
  EMAIL_SUBJECT varchar(250),
  TEXT_MESSAGE varchar(7000) NOT NULL DEFAULT '',
  PRIORITY int NOT NULL DEFAULT -1,
  HTML_CONTENT varchar(7000) NOT NULL DEFAULT '',
  FOLDER_ID int,
  SENT_DATE Timestamp NOT NULL,
  RECEIVED_DATE Timestamp,
  

  CONSTRAINT EMAILS_SENDER_EMAILADRESS_ID_EMAILADRESSES FOREIGN KEY (SENDER_EMAILADRESS_ID) REFERENCES EMAILADRESSES(ID),
  CONSTRAINT EMAILS_FOLDER_ID_FOLDERS FOREIGN KEY (FOLDER_ID) REFERENCES FOLDERS(ID)
);

CREATE TABLE EMAILS_TO_EMAILADRESSES (
EMAIL_ID int,
EMAILADRESSES_ID int,

CONSTRAINT EMAILS_EMAIL_ID_EMAILS FOREIGN KEY (EMAIL_ID) REFERENCES EMAILS(ID),
CONSTRAINT EMAILS_EMAILADRESSES_ID_EMAILADRESSES FOREIGN KEY (EMAILADRESSES_ID) REFERENCES EMAILADRESSES(ID)
);

CREATE TABLE EMAILS_CC_EMAILADRESSES (
EMAIL_ID int,
EMAILADRESSES_ID int,

CONSTRAINT EMAILS_CC_EMAILADRESSES_EMAIL_ID_EMAILS FOREIGN KEY (EMAIL_ID) REFERENCES EMAILS(ID),
CONSTRAINT EMAILS_CC_EMAILADRESSES_EMAILADRESSES_ID_EMAILADRESSES FOREIGN KEY (EMAILADRESSES_ID) REFERENCES EMAILADRESSES(ID)
);

CREATE TABLE EMAILS_BCC_EMAILADRESSES (
EMAIL_ID int,
EMAILADRESSES_ID int,

CONSTRAINT EMAILS_BCC_EMAILADRESSES_EMAIL_ID_EMAILS FOREIGN KEY (EMAIL_ID) REFERENCES EMAILS(ID),
CONSTRAINT EMAILS_BCC_EMAILADRESSES_EMAILADRESSES_ID_EMAILADRESSES FOREIGN KEY (EMAILADRESSES_ID) REFERENCES EMAILADRESSES(ID)
);

CREATE TABLE EMAILS_EMBEDED_ATTACHMENTS (
EMAIL_ID int,
ATTACHMENTS_ID int,

CONSTRAINT EMAILS_EMBEDED_ATTACHMENTS_EMAIL_ID_EMAILS FOREIGN KEY (EMAIL_ID) REFERENCES EMAILS(ID),
CONSTRAINT EMAILS_EMBEDED_ATTACHMENTS_ATTACHMENTS_ID_ATTACHMENTS FOREIGN KEY (ATTACHMENTS_ID) REFERENCES ATTACHMENTS(ID)
);

CREATE TABLE EMAILS_ATTACHMENTS (
EMAIL_ID int,
ATTACHMENTS_ID int,

CONSTRAINT EMAILS_ATTACHMENTS_EMAIL_ID_EMAILS FOREIGN KEY (EMAIL_ID) REFERENCES EMAILS(ID),
CONSTRAINT EMAILS_ATTACHMENTS_ATTACHMENTS_ID_ATTACHMENTS FOREIGN KEY (ATTACHMENTS_ID) REFERENCES ATTACHMENTS(ID)
);

